In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns 

In [2]:
df=pd.read_csv('/Users/vallirajasekar/Downloads/Titanic-Dataset.csv')

In [3]:
print(df.shape)
df.head()


(891, 12)


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [5]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [6]:
df.drop('Cabin',inplace=True,axis=1)

In [7]:
df['Age'].mean()

29.69911764705882

In [8]:
df['Age']=df['Age'].fillna(df['Age'].mean())

In [9]:
#df['Age'][df['Age']==29.69911764705882]

In [10]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Embarked  
0      0         A/5 21171   7.2500        S  
1      0          PC 17599  71.2833        C  
2      0  STON/O2. 3101282   7.9250        S  
3      0            113803  53.1000        S  
4      0            373450   8.0500        S

In [11]:
df['Ticket'].value_counts()

347082      7
CA. 2343    7
1601        7
3101295     6
CA 2144     6
           ..
9234        1
19988       1
2693        1
PC 17612    1
370376      1
Name: Ticket, Length: 681, dtype: int64

In [12]:
df_1=df.drop(['PassengerId','Name'],axis=1)

In [13]:
for column_name in df_1:
    print(df_1[column_name].value_counts())

0    549
1    342
Name: Survived, dtype: int64
3    491
1    216
2    184
Name: Pclass, dtype: int64
male      577
female    314
Name: Sex, dtype: int64
29.699118    177
24.000000     30
22.000000     27
18.000000     26
28.000000     25
            ... 
36.500000      1
55.500000      1
0.920000       1
23.500000      1
74.000000      1
Name: Age, Length: 89, dtype: int64
0    608
1    209
2     28
4     18
3     16
8      7
5      5
Name: SibSp, dtype: int64
0    678
1    118
2     80
5      5
3      5
4      4
6      1
Name: Parch, dtype: int64
347082      7
CA. 2343    7
1601        7
3101295     6
CA 2144     6
           ..
9234        1
19988       1
2693        1
PC 17612    1
370376      1
Name: Ticket, Length: 681, dtype: int64
8.0500     43
13.0000    42
7.8958     38
7.7500     34
26.0000    31
           ..
35.0000     1
28.5000     1
6.2375      1
14.0000     1
10.5167     1
Name: Fare, Length: 248, dtype: int64
S    644
C    168
Q     77
Name: Embarked, dtype: int64


In [14]:
df['Age'].describe()

count    891.000000
mean      29.699118
std       13.002015
min        0.420000
25%       22.000000
50%       29.699118
75%       35.000000
max       80.000000
Name: Age, dtype: float64

In [15]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Embarked  
0      0         A/5 21171   7.2500        S  
1      0          PC 17599  71.2833        C  
2      0  STON/O2. 3101282   7.9250        S  
3      0            113803  53.1000        S  
4      0            373450   8.0500        S

In [16]:
df['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [17]:
df.groupby(['Pclass','Survived'])['Pclass'].count()

Pclass  Survived
1       0            80
        1           136
2       0            97
        1            87
3       0           372
        1           119
Name: Pclass, dtype: int64

## In above the clear indication states that people who are survied by crash belongs to the Higher class and lot of death in lower category tickets 

In [18]:
df['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [19]:
df.groupby(['Sex','Survived'])['Pclass'].count()

Sex     Survived
female  0            81
        1           233
male    0           468
        1           109
Name: Pclass, dtype: int64

## In above, We can clearly see that survival rate of female is higher than man 

In [20]:
df.groupby(['Sex','Survived'])['Fare'].mean()

Sex     Survived
female  0           23.024385
        1           51.938573
male    0           21.960993
        1           40.821484
Name: Fare, dtype: float64

## In above category we can clearly see that lower average of mean states that survival rate is low whereas the higher the survival rate mean the made higher fare in the titanic

In [21]:
df.groupby(['Embarked','Survived'])['Fare'].mean()

Embarked  Survived
C         0           35.443335
          1           79.720926
Q         0           13.335904
          1           13.182227
S         0           20.743987
          1           39.547081
Name: Fare, dtype: float64

In [22]:
df.groupby(['Embarked','Survived'])['Survived'].count()

Embarked  Survived
C         0            75
          1            93
Q         0            47
          1            30
S         0           427
          1           217
Name: Survived, dtype: int64

In [23]:
df.groupby(['Embarked','Pclass'])['Pclass'].count()

Embarked  Pclass
C         1          85
          2          17
          3          66
Q         1           2
          2           3
          3          72
S         1         127
          2         164
          3         353
Name: Pclass, dtype: int64

In [24]:
df.groupby(['Pclass'])['Fare'].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [25]:
df_1

Survived  Pclass     Sex        Age  SibSp  Parch            Ticket  \
0           0       3    male  22.000000      1      0         A/5 21171   
1           1       1  female  38.000000      1      0          PC 17599   
2           1       3  female  26.000000      0      0  STON/O2. 3101282   
3           1       1  female  35.000000      1      0            113803   
4           0       3    male  35.000000      0      0            373450   
..        ...     ...     ...        ...    ...    ...               ...   
886         0       2    male  27.000000      0      0            211536   
887         1       1  female  19.000000      0      0            112053   
888         0       3  female  29.699118      1      2        W./C. 6607   
889         1       1    male  26.000000      0      0            111369   
890         0       3    male  32.000000      0      0            370376   

        Fare Embarked  
0     7.2500        S  
1    71.2833        C  
2     7.9250        S  
3    53.1000        S  
4     8.0500        S  
..       ...      ...  
886  13.0000        S  
887  30.0000        S  
888  23.4500        S  
889  30.0000        C  
890   7.7500        Q  

[891 rows x 9 columns]

In [26]:
df_1.shape

(891, 9)

In [27]:
df['Survived'].value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [28]:
X=df_1.drop('Survived',axis=1)

In [29]:
y=df_1.Survived

In [30]:
df_1=pd.get_dummies(df_1,columns=['Sex'],drop_first=True)


In [31]:
df_1.drop('Ticket',axis=1,inplace=True)

In [32]:
df_1['Age'].describe()

count    891.000000
mean      29.699118
std       13.002015
min        0.420000
25%       22.000000
50%       29.699118
75%       35.000000
max       80.000000
Name: Age, dtype: float64

In [33]:
age_bins = [0, 10, 30, 50, 90]  # Define your desired age bins
age_labels = ['C', 'M', 'A', 'E']  # Corresponding labels for the bins

# Use pd.cut() to create the 'Age_category' column
df_1['Age_category'] = pd.cut(df_1['Age'], bins=age_bins, labels=age_labels, right=False)


In [34]:
df_1

Survived  Pclass        Age  SibSp  Parch     Fare Embarked  Sex_male  \
0           0       3  22.000000      1      0   7.2500        S         1   
1           1       1  38.000000      1      0  71.2833        C         0   
2           1       3  26.000000      0      0   7.9250        S         0   
3           1       1  35.000000      1      0  53.1000        S         0   
4           0       3  35.000000      0      0   8.0500        S         1   
..        ...     ...        ...    ...    ...      ...      ...       ...   
886         0       2  27.000000      0      0  13.0000        S         1   
887         1       1  19.000000      0      0  30.0000        S         0   
888         0       3  29.699118      1      2  23.4500        S         0   
889         1       1  26.000000      0      0  30.0000        C         1   
890         0       3  32.000000      0      0   7.7500        Q         1   

    Age_category  
0              M  
1              A  
2              M  
3              A  
4              A  
..           ...  
886            M  
887            M  
888            M  
889            M  
890            A  

[891 rows x 9 columns]

In [35]:
df_1['Age_category_no']=df_1['Age_category'].map({'C':4,'M':1,'A':2,'E':3})

In [36]:
df_1['Embarked']=df_1['Embarked'].map({'C':3,'S':2,'Q':1})

In [37]:
df_1.drop('Age_category',axis=1,inplace=True)

In [38]:
df_1['Embarked']=df_1['Embarked'].fillna(df_1['Embarked'].mode()[0])

In [39]:
X=df_1.drop('Survived',axis=1)

In [40]:
y=df_1.Survived

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.8,stratify=y)

In [43]:
print(X_train,X_test,y_train,y_test)

     Pclass        Age  SibSp  Parch     Fare  Embarked  Sex_male  \
849       1  29.699118      1      0  89.1042       3.0         0   
242       2  29.000000      0      0  10.5000       2.0         1   
839       1  29.699118      0      0  29.7000       3.0         1   
74        3  32.000000      0      0  56.4958       2.0         1   
680       3  29.699118      0      0   8.1375       1.0         0   
..      ...        ...    ...    ...      ...       ...       ...   
203       3  45.500000      0      0   7.2250       3.0         1   
718       3  29.699118      0      0  15.5000       1.0         1   
398       2  23.000000      0      0  10.5000       2.0         1   
277       2  29.699118      0      0   0.0000       2.0         1   
518       2  36.000000      1      0  26.0000       2.0         0   

    Age_category_no  
849               1  
242               1  
839               1  
74                2  
680               1  
..              ...  
203              

In [44]:
from sklearn.linear_model import LogisticRegression

In [45]:
model=LogisticRegression()

In [46]:
model.fit(X_train,y_train)

/Applications/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [47]:
model.score(X_train,y_train)

0.8314606741573034

In [48]:
model.score(X_test,y_test)

0.791023842917251

In [50]:
y_pred=model.predict(X_test)

In [52]:
y_test[:10]

886    0
432    1
879    1
552    0
223    0
293    0
374    0
378    0
780    1
48     0
Name: Survived, dtype: int64

In [53]:
y_pred[:10]

array([0, 1, 1, 0, 0, 1, 1, 0, 1, 0])

In [49]:
from sklearn.metrics import classification_report,confusion_matrix

In [55]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.84      0.82      0.83       448
           1       0.71      0.74      0.72       265

    accuracy                           0.79       713
   macro avg       0.78      0.78      0.78       713
weighted avg       0.79      0.79      0.79       713



In [56]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.82      0.84      0.83       439
           1       0.74      0.71      0.72       274

    accuracy                           0.79       713
   macro avg       0.78      0.78      0.78       713
weighted avg       0.79      0.79      0.79       713



In [60]:
print(confusion_matrix(y_test,y_pred,labels=[0, 1]))

[[369  70]
 [ 79 195]]


In [62]:
print(confusion_matrix(y_test,y_pred))

[[369  70]
 [ 79 195]]


In [64]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.82      0.84      0.83       439
           1       0.74      0.71      0.72       274

    accuracy                           0.79       713
   macro avg       0.78      0.78      0.78       713
weighted avg       0.79      0.79      0.79       713



In [61]:
print(confusion_matrix(y_test,y_pred,labels=[1, 0]))

[[195  79]
 [ 70 369]]


In [70]:
print('Accracy_score:',((195+369)/(195+79+70+369)))

Accracy_score: 0.791023842917251


In [71]:
print('Precision_score:',195/(195+70))

Precision_score: 0.7358490566037735


In [72]:
print('Recall:',195/(195+79))

Recall: 0.7116788321167883


In [63]:
print(classification_report(y_test,y_pred,labels=[1, 0]))

              precision    recall  f1-score   support

           1       0.74      0.71      0.72       274
           0       0.82      0.84      0.83       439

    accuracy                           0.79       713
   macro avg       0.78      0.78      0.78       713
weighted avg       0.79      0.79      0.79       713



In [75]:
from sklearn.metrics import fbeta_score

In [76]:
fbeta_score(y_test, y_pred, average='macro', beta=0.5)


0.77893398661494

In [80]:
fbeta_score(y_test, y_pred, average='weighted', beta=0.5)


0.7900534196689051

In [79]:
fbeta_score(y_test, y_pred, average='weighted', beta=2)


0.7907190563986196